version: '3.9'

networks:
  bh_network:
    name: BH_Network
    driver: bridge

volumes:
  postgres-data:
    name: bh-postgres-data

services:
  web:
    build: 
      context: .
      dockerfile: BH.Case.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=BH_Case;Username=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - OPENAPI_SERVER_URL=http://localhost:8080
    depends_on:
      - db
    networks:
      - bh_network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: BH-swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost:8080/openapi/v1.json
    depends_on:
      - web 
    networks:
      - bh_network

  frontend:
    build:
      context: ./BH.Case.Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - web
    networks:
      - bh_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BH_Case
    ports:
      - "5433:5432"
    networks:
      - bh_network
    volumes:
      - postgres-data:/var/lib/postgresql/data